# Use an official MongoDB image as the base image
FROM mongo:latest

# Set the working directory to /data/db
WORKDIR /data/db

# Expose the MongoDB port (27017) to the host machine
EXPOSE 27017

# Start MongoDB when the container starts
CMD ["mongod"]

